# Generated by Django 2.1 on 2018-12-01 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_thumb'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='fetured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='published',
            field=models.BooleanField(default=False),
        ),
    ]
