# Generated by Django 2.1 on 2018-12-10 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20181210_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postcategory',
            name='cat_title',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
