# Generated by Django 2.1 on 2018-12-28 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_post_tags'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postcategory',
            options={'verbose_name': 'postcategory', 'verbose_name_plural': 'postcategories'},
        ),
    ]
